apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config-map
data:
  default.conf: |
    # Your configuration content here
    # Example:
    server {
      listen 80;
      server_name example.com;
      location / {
        root /usr/share/nginx/html;
        index index.html;
      }
    }
    server {
      listen 8080;

      location /api/v1/movies {
    proxy_pass http://movie-service-movie-service:8001/;
    }

      location /api/v1/casts {
    proxy_pass http://cast-service-cast-service:8002/;
    }

    }
