apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: cast-db-statefulset
  labels:
    app: cast-db
spec:
  replicas: 1  # Modifier le nombre de réplicas selon vos besoins
  selector:
    matchLabels:
      app: cast-db
  serviceName: cast-db
  template:
    metadata:
      labels:
        app: cast-db
    spec:
      containers:
      - name: cast-db-container
        image: postgres:12.1-alpine
        ports:
        - containerPort: 5432
        env:
        - name: POSTGRES_USER
          value: "cast_db_username" # Remplacez par le vrai nom d'utilisateur de la base de données
        - name: POSTGRES_PASSWORD
          value: "cast_db_password" # Remplacez par le vrai mot de passe de la base de données
        - name: POSTGRES_DB
          value: "cast_db_dev" # Remplacez par le vrai nom de la base de données
        volumeMounts:
        - name: cast-db-volume
          mountPath: /var/lib/postgresql/data
  volumeClaimTemplates:
  - metadata:
      name: cast-db-pvc
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 1Gi
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: movie-db-statefulset
  labels:
    app: movie-db
spec:
  replicas: 1  # Modifier le nombre de réplicas selon vos besoins
  selector:
    matchLabels:
      app: movie-db
  serviceName: movie-db
  template:
    metadata:
      labels:
        app: movie-db
    spec:
      containers:
      - name: movie-db-container
        image: postgres:12.1-alpine
        ports:
        - containerPort: 5432
        env:
        - name: POSTGRES_USER
          value: "movie_db_username" # Remplacez par le vrai nom d'utilisateur de la base de données
        - name: POSTGRES_PASSWORD
          value: "movie_db_password" # Remplacez par le vrai mot de passe de la base de données
        - name: POSTGRES_DB
          value: "movie_db_dev" # Remplacez par le vrai nom de la base de données
        volumeMounts:
        - name: movie-db-volume
          mountPath: /var/lib/postgresql/data
  volumeClaimTemplates:
  - metadata:
      name: movie-db-pvc
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 1Gi

